---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/aehlke/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Code/home/dotfiles
dotfiles_files:
  - .zshrc
  #- .gitignore
  #- .inputrc
  - .macos
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  #- doxygen
  - gettext
  #- gifsicle
  - git
  - github/gh/gh
  #- gpg
  #- httpie
  #- iperf
  #- libevent
  #- sqlite
  - nmap
  - ssh-copy-id
  #- cowsay
  #- readline
  - openssl
  - pv
  - zsh-history-substring-search
  # Above were from original author
  - mpv-iina
  - antigen

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - iina/homebrew-mpv-iina

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - vimr
  - miniforge

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
